// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package web

import (
	"github.com/bilal-bhatti/zipline/example/connectors"
)

// Injectors from wire.go:

func InitThingsService() (*ThingsService, error) {
	dataConnector, err := connectors.ProvideDataConnector()
	if err != nil {
		return nil, err
	}
	thingsService := &ThingsService{
		DataConnector: dataConnector,
	}
	return thingsService, nil
}
