// Code generated by Zipline. DO NOT EDIT.

// go:generate zipline
// +build !ziplinegen

package services

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/bilal-bhatti/zipline/example/models"
	"github.com/go-chi/chi"
)

type (
	ServicesContactsServiceCreateType func(context.Context, *models.ContactRequest) (*models.ContactResponse, error)
	ServicesContactsServiceGetOneType func(int) (*models.ContactResponse, error)
	ServicesContactsServiceUpdateType func(context.Context, int, models.ContactRequest) (*models.ContactResponse, error)
	ServicesEchoType                  func(EchoRequest) (EchoResponse, error)
)

func NewRouter() *chi.Mux {
	mux := chi.NewRouter()
	contacts := &ContactsService{}
	mux.Post("/contacts", ServicesContactsServiceCreateHandlerFunc(contacts.Create))
	mux.Get("/contacts/{id}", ServicesContactsServiceGetOneHandlerFunc(contacts.GetOne))
	mux.Post("/contacts/{id}", ServicesContactsServiceUpdateHandlerFunc(contacts.Update))
	mux.Post("/echo", ServicesEchoHandlerFunc(Echo))
	return mux
}

func ServicesContactsServiceCreateHandlerFunc(funk ServicesContactsServiceCreateType) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		var err error // tempory fix

		ctx := ProvideContext(req)

		contactRequest := &models.ContactRequest{}
		err = json.NewDecoder(req.Body).Decode(contactRequest)
		if err != nil {
			// write error response
			// invalid request error
			panic(err)
		}

		result, err := funk(ctx, contactRequest)
		if err != nil {
			// write error response
			// internal error
			panic(err)
		}

		w.WriteHeader(http.StatusOK)
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		err = json.NewEncoder(w).Encode(result)
		if err != nil {
			// write error response
			panic(err)
		}
	}
}

func ServicesContactsServiceGetOneHandlerFunc(funk ServicesContactsServiceGetOneType) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		var err error // tempory fix

		id, err := strconv.Atoi(chi.URLParam(req, "id"))
		if err != nil {
			// invalid request error
			panic(err)
		}

		result, err := funk(id)
		if err != nil {
			// write error response
			// internal error
			panic(err)
		}

		w.WriteHeader(http.StatusOK)
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		err = json.NewEncoder(w).Encode(result)
		if err != nil {
			// write error response
			panic(err)
		}
	}
}

func ServicesContactsServiceUpdateHandlerFunc(funk ServicesContactsServiceUpdateType) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		var err error // tempory fix

		ctx := ProvideContext(req)

		id, err := strconv.Atoi(chi.URLParam(req, "id"))
		if err != nil {
			// invalid request error
			panic(err)
		}

		contactRequest := models.ContactRequest{}
		err = json.NewDecoder(req.Body).Decode(&contactRequest)
		if err != nil {
			// write error response
			// invalid request error
			panic(err)
		}

		result, err := funk(ctx, id, contactRequest)
		if err != nil {
			// write error response
			// internal error
			panic(err)
		}

		w.WriteHeader(http.StatusOK)
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		err = json.NewEncoder(w).Encode(result)
		if err != nil {
			// write error response
			panic(err)
		}
	}
}

func ServicesEchoHandlerFunc(funk ServicesEchoType) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		var err error // tempory fix

		echoRequest := EchoRequest{}
		err = json.NewDecoder(req.Body).Decode(&echoRequest)
		if err != nil {
			// write error response
			// invalid request error
			panic(err)
		}

		result, err := funk(echoRequest)
		if err != nil {
			// write error response
			// internal error
			panic(err)
		}

		w.WriteHeader(http.StatusOK)
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		err = json.NewEncoder(w).Encode(result)
		if err != nil {
			// write error response
			panic(err)
		}
	}
}
