// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/bilal-bhatti/zipline/example/connectors"
)

// Injectors from wire.go:

// InitContactsService wires up the Contacts Service.
func InitContactsService() (*ContactsService, error) {
	dataConnector, err := connectors.ProvideDataConnector()
	if err != nil {
		return nil, err
	}
	contactsService := &ContactsService{
		DataConnector: dataConnector,
	}
	return contactsService, nil
}
